export const GET_COMMIC_BOOKS_FAILED = 'GET_COMMIC_BOOKS_FAILED';
export const SET_COMMIC_BOOKS = 'SET_COMMIC_BOOKS';
export const INIT_COMMIC_BOOKS = 'INIT_COMMIC_BOOKS';
export const SET_LOADING = 'SET_LOADING';
export const SELECT_BOOK = 'SELECT_BOOK';
export const SET_LOADING_BOOK = 'SET_LOADING_BOOK';

export const SEARCH = 'SEARCH';
export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';
export const CHANGE_CATEGORY = 'CHANGE_CATEGORY';
